version: '3.7'
services:
  dashboard: &dashboard
    restart: always         
    image: netsage/dashboard:1.11.0
    volumes:
      - .:/app
    ports:
      - 3000:3000
  dashboard_build:
    <<: *dashboard
    build:
      context: .
      dockerfile: ./docker/Dockerfile

