version: '3.0'
services:
  dashboard:
    image: netsage/dashboard:1.3.0
    build:
      context: .
      dockerfile: docker/Dockerfile
    #env_file: .env
    volumes:
      - .:/vagrant
    ports:
      - 3001:3000
